<?php
// Basic config from Drupal's settings.default.php
$databases = [];
$config_directories = [];
$settings['update_free_access'] = FALSE;
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';
$settings['file_scan_ignore_directories'] = [
  'node_modules',
  'bower_components',
];

$settings['install_profile'] = 'config_installer';
$settings['hash_salt'] = '10b203c732698899a2b6d1c5bdef6cd7b324c8f0ff21b5a8815de7be0e7921a5';

// Standard Acquia settings file.
if (isset($_ENV['AH_SITE_ENVIRONMENT'])) {
  include $app_root . '/' . $site_path . '/settings.acquia.php';
}

// In this codebase, config is managed by git and lives outside of the Drupal root.
$config_directories = [CONFIG_SYNC_DIRECTORY => '../conf/drupal/config'];

// Dev environment settings file provided by the-build.
if (file_exists($app_root . '/' . $site_path . '/settings.build.php')) {
  include $app_root . '/' . $site_path . '/settings.build.php';
}

// Local, per-developer config.
if (file_exists($app_root . '/' . $site_path . '/settings.local.php')) {
  include $app_root . '/' . $site_path . '/settings.local.php';
}

// <DDSETTINGS>
// Please don't edit anything between <DDSETTINGS> tags.
// This section is autogenerated by Acquia Dev Desktop.
if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/cld_prod_ukhealthcare_dev_default.inc')) {
  require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/cld_prod_ukhealthcare_dev_default.inc';
}
// </DDSETTINGS>
